#!/usr/bin/env python3
"""
Pulls published essays from the "Essays" Notion database and regenerates
thoughts/<slug>.html for each one, plus the card grid in thoughts.html.

Setup (one-time):
  1. Create an internal integration at https://www.notion.so/my-integrations
     and copy its "Internal Integration Secret".
  2. Open the "Essays" database inside the "Writing" page in Notion, click
     "..." -> "Connections" -> add your integration.
  3. export NOTION_TOKEN="secret_xxx"

Usage:
  python3 scripts/sync_notion.py

Requires only the Python standard library (no pip installs, no Node).
"""

import json
import os
import re
import subprocess
import sys
import urllib.request
from datetime import datetime
from pathlib import Path

NOTION_VERSION = "2022-06-28"
DATABASE_ID = "e0e422843dbe4e09b72f5555f7e6ea18"  # "Essays" database under the Writing page

ROOT = Path(__file__).resolve().parent.parent
THOUGHTS_DIR = ROOT / "thoughts"
IMAGES_DIR = THOUGHTS_DIR / "images"
THOUGHTS_INDEX = ROOT / "thoughts.html"

SYNC_START = "<!-- SYNC:START — regenerated by scripts/sync_notion.py, do not hand-edit between markers -->"
SYNC_END = "<!-- SYNC:END -->"

# fallback_credit is only set once we actually know the photographer for that
# category's placeholder image (images/*.jpg, used when a Notion row has no
# cover of its own) — leave it None rather than guess, since misattributing a
# stock photo is worse than not crediting it.
CATEGORY_META = {
    "Diving": {
        "class": "diving", "dot": "dot-diving", "fallback_img": "images/diving.jpg",
        "fallback_credit": {"name": "NEOM", "profile_url": "https://unsplash.com/@neom"},
    },
    "Game Design": {
        "class": "gamedesign", "dot": "dot-gamedesign", "fallback_img": "images/gamedesign.jpg",
        "fallback_credit": None,
    },
    "Book Review": {
        "class": "bookreview", "dot": "dot-bookreview", "fallback_img": "images/book.jpg",
        "fallback_credit": None,
    },
    "Life": {
        "class": "life", "dot": "dot-life", "fallback_img": "images/life.jpg",
        "fallback_credit": None,
    },
}

CARD_HEIGHTS = {
    "diving": 400, "gamedesign": 240, "bookreview": 180, "life": 300,
}

# Order determines which language becomes the "canonical" <slug>.html file when
# more than one language is published for the same Slug; the rest get a
# <slug>-<code>.html suffix.
LANGUAGE_ORDER = ["English", "Chinese"]
LANGUAGE_META = {
    "English": {"code": "en", "label": "EN"},
    "Chinese": {"code": "zh", "label": "中文"},
}

# Per-essay credit for custom Notion covers picked from Notion's built-in
# Unsplash browser (as opposed to a category fallback, or a self-uploaded
# photo which needs no credit). Keyed by the essay's Slug. Notion doesn't
# expose photographer info through its API, so these are recorded by hand
# whenever you tell me which photo you picked.
COVER_CREDITS = {
    "night-diving": {"name": "Chase Baker", "profile_url": "https://unsplash.com/@sandbarproductions"},
}


def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def notion_request(method, path, body=None):
    token = os.environ.get("NOTION_TOKEN")
    if not token:
        die("NOTION_TOKEN environment variable is not set. See the docstring at the top of this script.")
    url = f"https://api.notion.com/v1{path}"
    data = json.dumps(body).encode("utf-8") if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Notion-Version", NOTION_VERSION)
    req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        detail = e.read().decode("utf-8", errors="replace")
        die(f"Notion API {method} {path} failed: {e.code} {detail}")


def query_database(database_id):
    pages = []
    body = {
        "filter": {"property": "Published", "checkbox": {"equals": True}},
        "sorts": [{"property": "Date", "direction": "descending"}],
    }
    cursor = None
    while True:
        if cursor:
            body["start_cursor"] = cursor
        result = notion_request("POST", f"/databases/{database_id}/query", body)
        pages.extend(result.get("results", []))
        if result.get("has_more"):
            cursor = result.get("next_cursor")
        else:
            break
    return pages


def fetch_children(block_id):
    blocks = []
    cursor = None
    while True:
        path = f"/blocks/{block_id}/children?page_size=100"
        if cursor:
            path += f"&start_cursor={cursor}"
        result = notion_request("GET", path)
        blocks.extend(result.get("results", []))
        if result.get("has_more"):
            cursor = result.get("next_cursor")
        else:
            break
    for block in blocks:
        if block.get("has_children"):
            block["_children"] = fetch_children(block["id"])
    return blocks


def escape_html(text):
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def render_rich_text(rich_text):
    out = []
    for rt in rich_text:
        text = escape_html(rt.get("plain_text", ""))
        ann = rt.get("annotations", {})
        if ann.get("code"):
            text = f"<code>{text}</code>"
        if ann.get("strikethrough"):
            text = f"<s>{text}</s>"
        if ann.get("italic"):
            text = f"<em>{text}</em>"
        if ann.get("bold"):
            text = f"<strong>{text}</strong>"
        href = rt.get("href")
        if href:
            text = f'<a href="{escape_html(href)}" target="_blank" rel="noopener">{text}</a>'
        out.append(text)
    return "".join(out)


def download_image(url, dest_path):
    req = urllib.request.Request(url)
    with urllib.request.urlopen(req) as resp:
        dest_path.write_bytes(resp.read())
    return convert_if_unsupported(dest_path)


def convert_if_unsupported(path):
    """Browsers can't render HEIC/HEIF (common for photos uploaded to Notion
    straight from an iPhone), so convert to JPEG via macOS's built-in `sips`
    and swap the file in place. Returns the (possibly new) path."""
    if path.suffix.lower() not in (".heic", ".heif"):
        return path
    jpg_path = path.with_suffix(".jpg")
    subprocess.run(
        ["sips", "-s", "format", "jpeg", str(path), "--out", str(jpg_path)],
        check=True, capture_output=True,
    )
    path.unlink()
    return jpg_path


def image_url_and_ext(image_block):
    img = image_block["image"]
    url = img["external"]["url"] if img["type"] == "external" else img["file"]["url"]
    ext = os.path.splitext(url.split("?")[0])[1] or ".jpg"
    return url, ext


def render_blocks(blocks, slug, image_counter):
    html_parts = []
    i = 0
    while i < len(blocks):
        block = blocks[i]
        btype = block["type"]

        if btype in ("bulleted_list_item", "numbered_list_item"):
            tag = "ul" if btype == "bulleted_list_item" else "ol"
            items = []
            while i < len(blocks) and blocks[i]["type"] == btype:
                item = blocks[i]
                text = render_rich_text(item[btype]["rich_text"])
                if item.get("_children"):
                    text += render_blocks(item["_children"], slug, image_counter)
                items.append(f"<li>{text}</li>")
                i += 1
            html_parts.append(f"<{tag}>{''.join(items)}</{tag}>")
            continue

        if btype == "paragraph":
            text = render_rich_text(block["paragraph"]["rich_text"])
            html_parts.append(f"<p>{text}</p>" if text else "")
        elif btype in ("heading_1", "heading_2", "heading_3"):
            level = {"heading_1": "h2", "heading_2": "h2", "heading_3": "h3"}[btype]
            text = render_rich_text(block[btype]["rich_text"])
            html_parts.append(f"<{level}>{text}</{level}>")
        elif btype == "quote":
            text = render_rich_text(block["quote"]["rich_text"])
            html_parts.append(f"<blockquote>{text}</blockquote>")
        elif btype == "code":
            text = render_rich_text(block["code"]["rich_text"])
            html_parts.append(f"<pre><code>{text}</code></pre>")
        elif btype == "divider":
            html_parts.append("<hr />")
        elif btype == "image":
            image_counter[0] += 1
            url, ext = image_url_and_ext(block)
            dest = download_image(url, IMAGES_DIR / f"{slug}-{image_counter[0]}{ext}")
            filename = dest.name
            caption = render_rich_text(block["image"].get("caption", []))
            html_parts.append(f'<img src="images/{filename}" alt="{caption or slug}" />')
            if caption:
                html_parts.append(f"<p><em>{caption}</em></p>")
        # other block types (callout, toggle, etc.) are skipped for now

        i += 1
    return "\n".join(p for p in html_parts if p)


def slugify(title):
    slug = title.lower().strip()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    return slug.strip("-")


def plain_text_of(rich_text_prop):
    return "".join(rt.get("plain_text", "") for rt in rich_text_prop)


def get_cover(page, slug):
    cover = page.get("cover")
    if not cover:
        return None
    url = cover["external"]["url"] if cover["type"] == "external" else cover["file"]["url"]
    ext = os.path.splitext(url.split("?")[0])[1] or ".jpg"
    dest = download_image(url, IMAGES_DIR / f"{slug}-cover{ext}")
    return f"images/{dest.name}"


ESSAY_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{title} — Jingrong Chen</title>
  <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🐠</text></svg>">
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-7GHFT5PYBY"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){{dataLayer.push(arguments);}}
    gtag('js', new Date());
    gtag('config', 'G-7GHFT5PYBY');
  </script>
  <link rel="stylesheet" href="../style.css" />
  <style>
    .post-page {{
      min-height: 100vh;
      padding: 5rem 0 6rem;
      position: relative;
      overflow: hidden;
    }}

    .post-wrap {{
      max-width: 680px;
      margin: 0 auto;
      position: relative;
      z-index: 1;
    }}

    .back-link {{
      display: inline-flex;
      align-items: center;
      gap: 0.35rem;
      font-size: 0.75rem;
      font-weight: 600;
      letter-spacing: 0.12em;
      text-transform: uppercase;
      color: var(--text-muted);
      margin-bottom: 3rem;
      transition: color 0.2s;
      text-decoration: none;
    }}
    .back-link:hover {{ color: var(--accent); }}
    .back-link svg {{ width: 15px; height: 15px; }}

    .post-tag {{
      display: inline-block;
      font-size: 0.7rem;
      font-weight: 700;
      letter-spacing: 0.1em;
      text-transform: uppercase;
      padding: 0.25rem 0.65rem;
      border-radius: 999px;
      margin-bottom: 1.25rem;
      background: rgba(0,180,216,0.15);
      color: #00B4D8;
    }}

    .post-title {{
      font-size: clamp(1.8rem, 5vw, 2.8rem);
      font-weight: 800;
      color: rgba(255,255,255,0.92);
      line-height: 1.2;
      margin: 0 0 1rem;
    }}

    .post-date {{
      font-size: 0.8rem;
      color: var(--text-muted);
      letter-spacing: 0.05em;
      margin-bottom: 2.5rem;
      display: block;
    }}

    .post-divider {{
      border: none;
      border-top: 1px solid rgba(255,255,255,0.08);
      margin-bottom: 2.5rem;
    }}

    .post-body {{
      font-size: 1.05rem;
      line-height: 1.85;
      color: rgba(255,255,255,0.72);
    }}

    .post-body p {{ margin-bottom: 1.5rem; }}
    .post-body p:last-child {{ margin-bottom: 0; }}
    .post-body h2, .post-body h3 {{ color: rgba(255,255,255,0.92); margin: 2rem 0 1rem; }}
    .post-body ul, .post-body ol {{ margin: 0 0 1.5rem 1.4rem; }}
    .post-body li {{ margin-bottom: 0.5rem; }}
    .post-body blockquote {{
      border-left: 3px solid var(--accent);
      padding-left: 1rem;
      margin: 0 0 1.5rem;
      font-style: italic;
      color: rgba(255,255,255,0.85);
    }}
    .post-body pre {{
      background: rgba(255,255,255,0.05);
      border-radius: 8px;
      padding: 1rem;
      overflow-x: auto;
      margin: 0 0 1.5rem;
    }}
    .post-body img {{ max-width: 100%; border-radius: 8px; margin: 0 0 1rem; }}
    .post-body hr {{ border: none; border-top: 1px solid rgba(255,255,255,0.08); margin: 2rem 0; }}

    .lang-switch {{
      display: flex;
      gap: 0.6rem;
      align-items: center;
      font-size: 0.75rem;
      font-weight: 600;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      margin-bottom: 1.5rem;
    }}
    .lang-switch a {{ color: var(--text-muted); text-decoration: none; transition: color 0.2s; }}
    .lang-switch a:hover {{ color: var(--accent); }}
    .lang-switch .lang-current {{ color: var(--accent); }}
    .lang-switch .lang-sep {{ color: rgba(255,255,255,0.2); }}

    .post-credit {{
      font-size: 0.78rem;
      color: var(--text-muted);
      margin-top: 3rem;
      padding-top: 1.5rem;
      border-top: 1px solid rgba(255,255,255,0.08);
    }}
    .post-credit a {{ color: var(--text-muted); text-decoration: underline; text-underline-offset: 2px; }}
    .post-credit a:hover {{ color: var(--accent); }}
  </style>
</head>
<body>

  <!-- HAMBURGER -->
  <button class="hamburger dark fade-in" id="hamburger" aria-label="Open menu">
    <span></span>
    <span></span>
  </button>

  <!-- MENU OVERLAY -->
  <div class="menu-overlay" id="menuOverlay">
    <nav class="menu-nav">
      <a href="../index.html#about"  class="menu-link">About Me</a>
      <a href="../procreate.html"    class="menu-link">Procreate Art</a>
      <a href="../film-shots.html"   class="menu-link">Film Shots</a>
      <a href="../thoughts.html"     class="menu-link active">On My Mind</a>
    </nav>
  </div>

  <!-- BUBBLES -->
  <canvas id="bubbleCanvas" class="visible"></canvas>

  <main class="post-page">
    <div class="ambient-light"></div>
    <div class="ambient-light ambient-light--right"></div>
    <div class="container">
      <div class="post-wrap">

        <a href="../thoughts.html" class="back-link">
          <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <polyline points="15 18 9 12 15 6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
          All Posts
        </a>

        {lang_switch}
        <span class="post-tag">{category}</span>
        <h1 class="post-title">{title}</h1>
        <span class="post-date">{date_display}</span>

        <hr class="post-divider" />

        <div class="post-body">
          {body_html}
        </div>
        {credit_html}

      </div>
    </div>
  </main>

  <footer class="footer">
    <div class="footer-icons">
      <a href="https://www.linkedin.com/in/chenjingrong/" target="_blank" rel="noopener" aria-label="LinkedIn">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" width="20" height="20">
          <path d="M20.45 20.45h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.354V9h3.414v1.561h.046c.476-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.284zM5.337 7.433a2.062 2.062 0 1 1 0-4.124 2.062 2.062 0 0 1 0 4.124zM6.87 20.45H3.803V9H6.87v11.45zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
        </svg>
      </a>
      <a href="mailto:jingronc@gmail.com" aria-label="Email">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" width="20" height="20">
          <rect x="2" y="4" width="20" height="16" rx="2"/>
          <polyline points="2,4 12,13 22,4"/>
        </svg>
      </a>
    </div>
    <p>Made with 💙 by Jingrong Chen</p>
  </footer>

  <script>
    const hamburger   = document.getElementById('hamburger');
    const menuOverlay = document.getElementById('menuOverlay');
    const menuLinks   = document.querySelectorAll('.menu-link');

    hamburger.addEventListener('click', () => {{
      const isOpen = menuOverlay.classList.toggle('is-open');
      hamburger.classList.toggle('is-open', isOpen);
      document.body.style.overflow = isOpen ? 'hidden' : '';
    }});
    menuLinks.forEach(link => {{
      link.addEventListener('click', () => {{
        menuOverlay.classList.remove('is-open');
        hamburger.classList.remove('is-open');
        document.body.style.overflow = '';
      }});
    }});

    const canvas = document.getElementById('bubbleCanvas');
    const ctx    = canvas.getContext('2d');

    function resize() {{
      canvas.width  = window.innerWidth;
      canvas.height = window.innerHeight;
    }}
    resize();
    window.addEventListener('resize', resize, {{ passive: true }});

    function randomBubble() {{
      return {{
        x:       Math.random() * canvas.width,
        y:       canvas.height + Math.random() * 200,
        r:       Math.random() * 3 + 1,
        speed:   Math.random() * 0.5 + 0.2,
        opacity: Math.random() * 0.35 + 0.05,
        drift:   (Math.random() - 0.5) * 0.4,
      }};
    }}

    const bubbles = [];
    for (let i = 0; i < 80; i++) {{
      const b = randomBubble();
      b.y = Math.random() * canvas.height;
      bubbles.push(b);
    }}

    function drawBubble(b) {{
      ctx.beginPath();
      ctx.arc(b.x, b.y, b.r, 0, Math.PI * 2);
      ctx.strokeStyle = `rgba(94, 207, 218, ${{b.opacity}})`;
      ctx.lineWidth   = 0.8;
      ctx.stroke();

      ctx.beginPath();
      ctx.arc(b.x, b.y, b.r * 0.4, 0, Math.PI * 2);
      ctx.fillStyle = `rgba(180, 240, 245, ${{b.opacity * 0.5}})`;
      ctx.fill();

      b.y -= b.speed;
      b.x += b.drift;
      if (b.y + b.r < 0) Object.assign(b, randomBubble());
    }}

    function animate() {{
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      bubbles.forEach(drawBubble);
      requestAnimationFrame(animate);
    }}
    animate();
  </script>
</body>
</html>
"""

CARD_TEMPLATE = """        <a class="post-card post-card--{cat_class}" href="thoughts/{slug}.html" data-category="{cat_class}">
          <div class="post-card-img" style="background-image: url('thoughts/{card_img}')"></div>
          <div class="post-card-body">
            <h2 class="post-title">{title}</h2>
            <div class="post-meta">
              <span class="post-dot {dot_class}"></span>
              <span class="post-meta-text">{category} &nbsp;·&nbsp; {date_display}</span>
            </div>
          </div>
        </a>"""


def build_credit_html(slug, cover_rel, meta):
    if cover_rel == meta["fallback_img"]:
        credit = meta["fallback_credit"]
    else:
        credit = COVER_CREDITS.get(slug)
    if not credit:
        return ""
    return (
        '<p class="post-credit">Cover photo by '
        f'<a href="{escape_html(credit["profile_url"])}" target="_blank" rel="noopener">{escape_html(credit["name"])}</a>'
        ' on <a href="https://unsplash.com" target="_blank" rel="noopener">Unsplash</a></p>'
    )


def build_lang_switch(group, current_language, filenames):
    present = [lang for lang in LANGUAGE_ORDER if lang in group]
    if len(present) < 2:
        return ""
    parts = []
    for lang in present:
        label = LANGUAGE_META[lang]["label"]
        if lang == current_language:
            parts.append(f'<span class="lang-current">{label}</span>')
        else:
            parts.append(f'<a href="{filenames[lang]}">{label}</a>')
    return '<div class="lang-switch">' + '<span class="lang-sep">|</span>'.join(parts) + "</div>"


def main():
    THOUGHTS_DIR.mkdir(exist_ok=True)
    IMAGES_DIR.mkdir(exist_ok=True)

    pages = query_database(DATABASE_ID)
    if not pages:
        print("No published essays found (check the 'Published' checkbox in Notion).")

    # Pass 1: extract + render every published row, grouped by Slug so we can
    # tell which rows are translations of each other before writing files.
    groups = {}  # slug -> {language: row_dict}
    for page in pages:
        props = page["properties"]
        title = plain_text_of(props["Title"]["title"])
        if not title:
            continue
        category = (props.get("Category", {}).get("select") or {}).get("name")
        if category not in CATEGORY_META:
            print(f"warning: skipping '{title}' — missing/unknown Category")
            continue
        language = (props.get("Language", {}).get("select") or {}).get("name")
        if language not in LANGUAGE_META:
            print(f"warning: skipping '{title}' — missing/unknown Language")
            continue
        slug = plain_text_of(props.get("Slug", {}).get("rich_text", [])).strip() or slugify(title)
        if not slug:
            print(f"warning: skipping '{title}' — no Slug set and title has no ASCII fallback")
            continue

        date_prop = props.get("Date", {}).get("date")
        date_display = "Undated"
        if date_prop and date_prop.get("start"):
            dt = datetime.fromisoformat(date_prop["start"][:10])
            date_display = dt.strftime("%b %-d, %Y") if os.name != "nt" else dt.strftime("%b %d, %Y")

        block_id_safe = f"{slug}-{LANGUAGE_META[language]['code']}"
        blocks = fetch_children(page["id"])
        body_html = render_blocks(blocks, block_id_safe, [0])
        cover_rel = get_cover(page, block_id_safe) or CATEGORY_META[category]["fallback_img"]

        groups.setdefault(slug, {})[language] = {
            "title": title,
            "category": category,
            "date_display": date_display,
            "body_html": body_html,
            "cover_rel": cover_rel,
        }

    # Pass 2: for each slug, pick the canonical (primary) language for the
    # plain <slug>.html filename and the grid card; other languages get
    # <slug>-<code>.html and a lang-switch link back and forth.
    cards = []
    for slug, group in groups.items():
        present = [lang for lang in LANGUAGE_ORDER if lang in group]
        primary = present[0]
        filenames = {
            lang: f"{slug}.html" if lang == primary else f"{slug}-{LANGUAGE_META[lang]['code']}.html"
            for lang in present
        }

        for lang in present:
            row = group[lang]
            meta = CATEGORY_META[row["category"]]
            lang_switch = build_lang_switch(group, lang, filenames)
            credit_html = build_credit_html(slug, row["cover_rel"], meta)
            essay_html = ESSAY_TEMPLATE.format(
                title=escape_html(row["title"]),
                category=escape_html(row["category"]),
                date_display=escape_html(row["date_display"]),
                body_html=row["body_html"],
                lang_switch=lang_switch,
                credit_html=credit_html,
            )
            filename = filenames[lang]
            (THOUGHTS_DIR / filename).write_text(essay_html, encoding="utf-8")
            print(f"wrote thoughts/{filename}")

            if lang == primary:
                cards.append(CARD_TEMPLATE.format(
                    cat_class=meta["class"],
                    slug=slug,
                    card_img=row["cover_rel"],
                    title=escape_html(row["title"]),
                    dot_class=meta["dot"],
                    category=escape_html(row["category"]),
                    date_display=escape_html(row["date_display"]),
                ))

    index_html = THOUGHTS_INDEX.read_text(encoding="utf-8")
    if SYNC_START not in index_html or SYNC_END not in index_html:
        die(f"could not find sync markers in {THOUGHTS_INDEX}")
    before, rest = index_html.split(SYNC_START, 1)
    _, after = rest.split(SYNC_END, 1)
    new_block = SYNC_START + "\n" + "\n\n".join(cards) + "\n        " + SYNC_END
    THOUGHTS_INDEX.write_text(before + new_block + after, encoding="utf-8")
    print(f"updated {THOUGHTS_INDEX.relative_to(ROOT)} with {len(cards)} card(s)")


if __name__ == "__main__":
    main()
